name = "student"
main = "src/index.js"
compatibility_date = "2026-06-20"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "students-db"
database_id = "6450ef14-6fa3-47d8-83f1-80cfde2b9b7a"
